# Generated by Django 5.0.4 on 2024-06-25 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 25, 18, 47, 58, 684234)),
        ),
    ]
